### ISSUE TITLE
[2.0.x] String[] type is not supported

### ISSUE THREAD

**Issue by fbiville** [neo4j-contrib/neo4j-jdbc#58]
It currently fails like this:

```java
Caused by: java.lang.IllegalArgumentException: Could not serialize value 3 [Ljava.lang.String;@6a6afff2
	at org.neo4j.jdbc.internal.rest.JsonUtils.serialize(JsonUtils.java:83)
	at org.neo4j.jdbc.internal.rest.Statement.toJson(Statement.java:30)
	at org.neo4j.jdbc.internal.rest.Statement.toJson(Statement.java:55)
	at org.neo4j.jdbc.internal.rest.TransactionalQueryExecutor.post(TransactionalQueryExecutor.java:97)
	at org.neo4j.jdbc.internal.rest.TransactionalQueryExecutor.begin(TransactionalQueryExecutor.java:76)
	at org.neo4j.jdbc.internal.rest.TransactionalQueryExecutor.executeQuery(TransactionalQueryExecutor.java:214)
	at org.neo4j.jdbc.internal.Neo4jConnection.executeQuery(Neo4jConnection.java:370)
```

**Comment by fbiville** [comment]
All the following should be supported out of the box, I think:

- [ ] `boolean[]` 
- [ ] `Boolean[]`
- [x] `byte[]`
- [ ] `Byte[]`
- [ ] `short[]`
- [ ] `Short[]`
- [ ] `int[]`
- [ ] `Integer[]`
- [ ] `long[]`
- [ ] `Long[]`
- [ ] `float[]`
- [ ] `Float[]`
- [ ] `double[]`
- [ ] `Double[]`
- [ ] `char[]`
- [ ] `Char[]`
- [ ] `String[]`
